# Generated by Django 4.0.4 on 2022-06-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/user_profile/%d/%m/%y', verbose_name='Proile Pic'),
        ),
    ]
